<?xml version="1.0" ?>
<testsuite errors="0" failures="1" name="tests.TestCyl2-20141017150338" tests="3" time="1117.785">
	<testcase classname="tests.TestCyl2" name="test1D" time="1117.775"/>
	<testcase classname="tests.TestCyl2" name="testTime" time="0.003"/>
	<testcase classname="tests.TestCyl2" name="test2D" time="0.006">
		<failure message="0.052822284 != 0.038176446608393366 within 2 places" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 96, in test2D
AssertionError: 0.052822284 != 0.038176446608393366 within 2 places
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[CylinderModel2
]]>	</system-out>
	<system-err>
<![CDATA[pydev debugger: Unable to find module to reload: "sansmodels.test.utest_models".
pydev debugger: Unable to find module to reload: "sansmodels.test.utest_models".
]]>	</system-err>
</testsuite>
