<?xml version="1.0" ?>
<testsuite errors="4" failures="0" name="tests.TestCyl2-20141023145739" tests="4" time="0.000">
	<testcase classname="tests.TestCyl2" name="test1D" time="0.000">
		<error message="No module named CylinderModel2" type="ImportError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 83, in setUp
    from sans.models.CylinderModel2 import CylinderModel2
ImportError: No module named CylinderModel2
]]>		</error>
	</testcase>
	<testcase classname="tests.TestCyl2" name="test2D" time="0.000">
		<error message="No module named CylinderModel2" type="ImportError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 83, in setUp
    from sans.models.CylinderModel2 import CylinderModel2
ImportError: No module named CylinderModel2
]]>		</error>
	</testcase>
	<testcase classname="tests.TestCyl2" name="test2DXY" time="0.000">
		<error message="No module named CylinderModel2" type="ImportError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 83, in setUp
    from sans.models.CylinderModel2 import CylinderModel2
ImportError: No module named CylinderModel2
]]>		</error>
	</testcase>
	<testcase classname="tests.TestCyl2" name="testTime" time="0.000">
		<error message="No module named CylinderModel2" type="ImportError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 83, in setUp
    from sans.models.CylinderModel2 import CylinderModel2
ImportError: No module named CylinderModel2
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
