<?xml version="1.0" ?>
<testsuite errors="0" failures="2" name="tests.TestCyl2-20141020120005" tests="4" time="0.216">
	<testcase classname="tests.TestCyl2" name="test1D" time="0.212"/>
	<testcase classname="tests.TestCyl2" name="testTime" time="0.001"/>
	<testcase classname="tests.TestCyl2" name="test2D" time="0.001">
		<failure message="0.052822284 != 0.038176446608393366 within 2 places" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 100, in test2D
    self.assertAlmostEqual(self.comp.run([0.2, 2.5]), 0.038176446608393366, 2)
AssertionError: 0.052822284 != 0.038176446608393366 within 2 places
]]>		</failure>
	</testcase>
	<testcase classname="tests.TestCyl2" name="test2DXY" time="0.001">
		<failure message="23.035643 != 14.89 within 2 places" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 106, in test2DXY
    self.assertAlmostEqual(self.comp.runXY([0.01, 0.02]), 14.89, 2)
AssertionError: 23.035643 != 14.89 within 2 places
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[CylinderModel2
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
